### ISSUE TITLE
Error installing certificate on Linux

### ISSUE THREAD

**Issue by seidnerj** [ProxymanApp/proxyman-windows-linux#389]
This fails with the following error:
```
Error installing certificate:  No polkit authentication agent found.
Error occurred in handler for 'CERTIFICATE_SERVICE_INSTALL_CERTIFICATE_AUTOMATICALLY': Error: No polkit authentication agent found.
    at Object.throw (/tmp/.mount_ProxymPqXNXx/resources/app.asar/dist/main/webpack:/proxyman/src/main/services/certificate-service.ts:79:17)
    at Generator.throw (<anonymous>)
    at o (/tmp/.mount_ProxymPqXNXx/resources/app.asar/dist/main/webpack:/proxyman/src/main/services/certificate-service.ts:13:24)
```

Screenshot:
<img width="1625" alt="Screenshot 2024-03-18 at 21 21 03" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/4147381/6e37b019-b014-4259-b7c6-83c5a8f3152d">

Log file:
[install_certificate_error.log](https://github.com/ProxymanApp/proxyman-windows-linux/files/14641462/install_certificate_error.log)

Also, when "Open Document" in the error dialog box one is referred to "https://docs.proxyman.io/proxyman-windows/install-certificate", i.e. instructions to manually install a certificate on Windows, rather than on Linux. Unfortunately I didn't find an equivalent version for Linux. I even tried guessing a url, i.e. "https://docs.proxyman.io/proxyman-linux/install-certificate" but this doesn't seem to exist.

**Comment by NghiaTranUIT** [comment]
Hi @seidnerj what Linux distro (and version) you're using?

Currently, Proxyman Linux works well with the Ubuntu (20 or 22). For others, it depends

**Comment by seidnerj** [comment]
@NghiaTranUIT, I am using Ubuntu 22 running on Azure and connecting via X11:
Linux <HOSTNAME> 6.5.0-1016-azure #16~22.04.1-Ubuntu SMP Fri Feb 16 15:42:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

It would be great if you could at least tell me how to generate/install a certificate manually on Linux in the meanwhile. 
I also couldn't find the "Auto Start Recording Traffic at Launch" feature in he UI, could I edit config.json manually and switch this off?

**Comment by kics223w1** [comment]
@seidnerj  You can turn this off and the application will not record the traffic at launch. 
This is in the Preferences dialog, click `Ctrl+,` or go to `Proxyman -> Preferences (at the top left)` to open this dialog.

<img width="1504" alt="image" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/77295189/40ef1a9a-4e17-4fce-a8a2-7cd0ee967fd7">

**Comment by seidnerj** [comment]
> @seidnerj You can turn this off and the application will not record the traffic at launch. This is in the Preferences dialog, click `Ctrl+,` or go to `Proxyman -> Preferences (at the top left)` to open this dialog.
> 
> <img alt="image" width="1504" src="https://private-user-images.githubusercontent.com/77295189/314041164-40ef1a9a-4e17-4fce-a8a2-7cd0ee967fd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTY5NzIsIm5iZiI6MTcxMDg1NjY3MiwicGF0aCI6Ii83NzI5NTE4OS8zMTQwNDExNjQtNDBlZjFhOWEtNGUxNy00ZmNlLWE4YTItN2NkMGVlOTY3ZmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEzNTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYmE5ZTk4NTVmOGJkMTNlZWZhNzI2MGYyM2VhMzY4NDgzOTI1ZjIyOTI0NTRmZjEwZmY1YjYxMzgwNzdlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EoYJdEz9vkHDa5V7bwJT83Z1VyEmDOxnGlRrqhLt_Z4">

That's the the override for the proxy settings, not the start recording...

**Comment by runetech0** [comment]
Having same issue. Is there any update on this one?

**Comment by NghiaTranUIT** [comment]
@runetech0 What Linux distro you're using?

I will add a Manual Tab to help you manually install the certificate your Linux Trust Store

**Comment by NghiaTranUIT** [comment]
@runetech0 can you install `lxpolkit` to your system?

I tested on Ubuntu 22 and it's already installed in the system. Not sure why you don't have it.

**Comment by runetech0** [comment]
> @runetech0 What Linux distro you're using?
> 
> I will add a Manual Tab to help you manually install the certificate your Linux Trust Store

I'm using Ubuntu 24 with i3wm.
I have already tried installing lxpolkit but no luck.

**Comment by paulschreiber** [comment]
What is the workaround? I have a Pixelbook, which uses Debian 12.
